/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tablas;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author laura
 */
public class Respaldo extends javax.swing.JFrame {

    /**
     * Creates new form Donadores_Backup
     */
    public Respaldo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tabla_Transacciones = new javax.swing.JPanel();
        btn_Respaldo_ = new javax.swing.JButton();
        btn_Menu = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla_Backup_ = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Tabla_Transacciones.setBackground(new java.awt.Color(153, 153, 255));

        btn_Respaldo_.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        btn_Respaldo_.setForeground(new java.awt.Color(153, 102, 255));
        btn_Respaldo_.setText("Respaldo");
        btn_Respaldo_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Respaldo_ActionPerformed(evt);
            }
        });

        btn_Menu.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        btn_Menu.setForeground(new java.awt.Color(153, 102, 255));
        btn_Menu.setText("Menú");
        btn_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MenuActionPerformed(evt);
            }
        });

        Tabla_Backup_.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "ID_Donador", "Dirección", "Fecha", "Metodo Pago", "Categoría"
            }
        ));
        jScrollPane2.setViewportView(Tabla_Backup_);

        javax.swing.GroupLayout Tabla_TransaccionesLayout = new javax.swing.GroupLayout(Tabla_Transacciones);
        Tabla_Transacciones.setLayout(Tabla_TransaccionesLayout);
        Tabla_TransaccionesLayout.setHorizontalGroup(
            Tabla_TransaccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tabla_TransaccionesLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(btn_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137)
                .addComponent(btn_Respaldo_)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Tabla_TransaccionesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Tabla_TransaccionesLayout.setVerticalGroup(
            Tabla_TransaccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tabla_TransaccionesLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(Tabla_TransaccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Menu)
                    .addComponent(btn_Respaldo_))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tabla_Transacciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tabla_Transacciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Respaldo_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Respaldo_ActionPerformed
 // Cargar datos en Tabla_Backup desde el archivo CSV
    cargarDatosEnTablaBackup();

    // Mensaje de éxito
    JOptionPane.showMessageDialog(this, "Datos cargados en la tabla de respaldo.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
}
private void cargarDatosEnTablaBackup() {
    DefaultTableModel model = (DefaultTableModel) Tabla_Backup_.getModel();
    model.setRowCount(0); // Limpiar la tabla antes de cargar los nuevos datos

    try (BufferedReader br = new BufferedReader(new FileReader("respaldo_donadores.csv"))) {
        String line;
        while ((line = br.readLine()) != null) {
            String[] data = line.split(",");

            // Verificar que el arreglo 'data' tenga la cantidad correcta de elementos
            if (data.length == 6) {
                String nombre = data[0];
                String idDonador = data[1];
                String direccion = data[2];
                String fecha = data[3];
                String metodoPago = data[4];
                String categoria = data[5];

                // Agregar los datos a la tabla Tabla_Backup
                model.addRow(new Object[]{nombre, idDonador, direccion, fecha, metodoPago, categoria});
            }
        }
    } catch (IOException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error al cargar el respaldo a la tabla.", "Error", JOptionPane.ERROR_MESSAGE);
    }
}

    private static class Tabla_Backup {

        public Tabla_Backup() {
        }
    
    }//GEN-LAST:event_btn_Respaldo_ActionPerformed

    private void btn_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MenuActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        Menu ventanaMenu = new Menu();

        // Mostrar la ventana Menu
        ventanaMenu.setVisible(true);

        // Cerrar la ventana actual (Tabla_Universidad)
        this.dispose();
    }//GEN-LAST:event_btn_MenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Respaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Respaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Respaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Respaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Respaldo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla_Backup_;
    private javax.swing.JPanel Tabla_Transacciones;
    private javax.swing.JButton btn_Menu;
    private javax.swing.JButton btn_Respaldo_;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

}
