/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tablas;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author laura
 */
public class Vistas extends javax.swing.JFrame {

    /**
     * Creates new form Vistas
     */
    public Vistas() {
        initComponents();
    }
    
    private void initializeTable() {
     DefaultTableModel model = new DefaultTableModel(
            new Object[][]{}, // Datos iniciales vacíos
            new String[]{"ID_Donador", "Nombre", "Direccion", "Fecha", "Metodo_Pago", "Categoria", "Monto", "FechaTransaccion"} // Nombres de columnas
        );
        Tabla_Vistas.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tabla_Transacciones = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Vistas = new javax.swing.JTable();
        btn_Vistas_ = new javax.swing.JButton();
        btn_Menu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Tabla_Transacciones.setBackground(new java.awt.Color(153, 153, 255));

        Tabla_Vistas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID_Donador", "Nombre", "Direccion", "Fecha", "Metodo_Pago", "Categoria"
            }
        ));
        Tabla_Vistas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Tabla_VistasKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla_Vistas);

        btn_Vistas_.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        btn_Vistas_.setForeground(new java.awt.Color(153, 102, 255));
        btn_Vistas_.setText("Vistas");
        btn_Vistas_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Vistas_ActionPerformed(evt);
            }
        });

        btn_Menu.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        btn_Menu.setForeground(new java.awt.Color(153, 102, 255));
        btn_Menu.setText("Menú");
        btn_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Tabla_TransaccionesLayout = new javax.swing.GroupLayout(Tabla_Transacciones);
        Tabla_Transacciones.setLayout(Tabla_TransaccionesLayout);
        Tabla_TransaccionesLayout.setHorizontalGroup(
            Tabla_TransaccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tabla_TransaccionesLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Tabla_TransaccionesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Menu)
                .addGap(70, 70, 70)
                .addComponent(btn_Vistas_)
                .addGap(170, 170, 170))
        );
        Tabla_TransaccionesLayout.setVerticalGroup(
            Tabla_TransaccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tabla_TransaccionesLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Tabla_TransaccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Vistas_)
                    .addComponent(btn_Menu))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tabla_Transacciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tabla_Transacciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Vistas_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Vistas_ActionPerformed
        // TODO add your handling code here: 
       try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/Univeersidaad", "laura", "laura");
            CallableStatement stmt = conn.prepareCall("{call ObtenerDatosVistaOracle()}");

            // Ejecutar el procedimiento almacenado
            ResultSet rs = stmt.executeQuery();

            // Procesar los resultados
            DefaultTableModel model = (DefaultTableModel) Tabla_Vistas.getModel();
            model.setRowCount(0); // Limpiar la tabla antes de mostrar nuevos datos

            while (rs.next()) {
                Object[] fila = {
                    rs.getInt("ID_Donador"),
                    rs.getString("Nombre"),
                    rs.getString("Direccion"),
                    rs.getDate("Fecha"),
                    rs.getString("Metodo_Pago"),
                    rs.getString("Categoria"),
                    rs.getDouble("Monto"),
                    rs.getDate("FechaTransaccion")
                };
                model.addRow(fila);
            }

            rs.close();
            stmt.close();
            conn.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void llamarProcedimientoAlmacenado() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    private static class Tabla_Vistas {

        public Tabla_Vistas() {
        }

    }//GEN-LAST:event_btn_Vistas_ActionPerformed
/*  private void llamarProcedimientoAlmacenado() {
    try {
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/Univeersidaad", "laura", "laura");
        CallableStatement stmt = conn.prepareCall("{call ObtenerDatosVistaOracle()}");

        // Ejecutar el procedimiento almacenado
        ResultSet rs = stmt.executeQuery();

        // Procesar los resultados
        DefaultTableModel model = (DefaultTableModel) Tabla_Vistas.getModel();
        model.setRowCount(0); // Limpiar la tabla antes de mostrar nuevos datos

        while (rs.next()) {
            Object[] fila = {
                rs.getInt("ID_Donador"),
                rs.getString("Nombre"),
                rs.getString("Direccion"),
                rs.getDate("Fecha"),
                rs.getString("Metodo_Pago"),
                rs.getString("Categoria"),
                rs.getDouble("Monto"),
                rs.getDate("FechaTransaccion")
            };
            model.addRow(fila);
        }

        rs.close();
        stmt.close();
        conn.close();
    } catch (SQLException e) {
        e.printStackTrace();
    }
}*/
    private void btn_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MenuActionPerformed
        // TODO add your handling code here:
        Menu ventanaMenu = new Menu();
    
    // Mostrar la ventana Menu
    ventanaMenu.setVisible(true);
    
    // Cerrar la ventana actual (Tabla_Universidad)
    this.dispose();
    
    }//GEN-LAST:event_btn_MenuActionPerformed

    private void Tabla_VistasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Tabla_VistasKeyPressed
        // TODO add your handling code here:
                llamarProcedimientoAlmacenado();

        
    }//GEN-LAST:event_Tabla_VistasKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vistas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Tabla_Transacciones;
    private javax.swing.JTable Tabla_Vistas;
    private javax.swing.JButton btn_Menu;
    private javax.swing.JButton btn_Vistas_;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private static class Tabla_Funcion_Almacenado {

        public Tabla_Funcion_Almacenado() {
        }
    }
}
